### PR TITLE
adding playmode functionality

### PR DESCRIPTION
**Pull request by ttenbergen**
I have never done a pull request or contributed to github so please be patient with me if I didn't do this the right way. 

I needed the loop functionality from the chip that is documented on P23 in https://cdn.sparkfun.com/assets/1/d/b/f/d/WT2003S-16S_Datasheet.pdf. Thought this would be useful to others and have wanted to contribute to something open source for a long time, so giving this a shot. If I need to do this differently please explain.

### CODE REVIEW

**Comment by nseidle** [comment]
Welcome to open source! Looks like a wonderful contribution. Thank you. The code looks good. My only complaint, and this is not just your contribution (I've seen it a few times), but sometimes git shows diff of the entire file instead of just the lines you changed (the [main cpp of your PR](https://github.com/sparkfun/SparkFun_WT2003S_MP3_Decoder_Arduino_Library/pull/1/files#diff-41aba1f1fd21b22174fe2e74ff0221b7) has this issue).

Doing some digging, it looks like your text editor may be modifying the line endings (from a \n to a \n\r or vice versa) so git thinks the entire file is changed. See [1](https://stackoverflow.com/questions/1889559/git-diff-to-ignore-m), [2](https://stackoverflow.com/questions/19593909/git-diff-sees-whole-file-as-changed-when-its-not).

It might be our line endings? Not sure. But this cpp is small enough I can see what code you've added. If this was a larger project we'd have to refuse the contrib until the diffs get sorted.

Thanks for this! Please keep it coming!

**Comment by oclyke** [comment]
Wonderful! Thank you for improving this library :D

**Comment by ttenbergen** [comment]
Thanks for integrating that change so quickly, it's neat to see this at
work!

I had noticed the diff looking like only some things changed in the arduino
code, and all in the other files. I had used Notepad++ for non-Arduino
files, and it is currently set to use Windows (CR LF) EOLs. I changed the
settings to actually display the line endings and you were correct: it used
different ones for the different files.

So I have learned what it would take to avoid this problem in the future.
If your next contributor has the same problem and also uses Notepad++, then
you can tell them they can make the EOLs visible with View -> Show Symbol
-> Show End of Line, and change the encoding with Edit -> EOL Conversion ->
<chose what the file has>.

**Comment by ttenbergen** [comment]
Actually, I have another question. I hope I am not abusing the system here.
I can't figure out what the library actually uses when i use
playTrackNumber. I tried to give it the track number, but that doesn't seem
to be it. I renamed the files to start with the same numbers as the track
#, and that's not it either. I also tried to use as parameter the sort
order in the last windows explorer view I used before ejecting the SD card,
because that actually seems to be what it suggests in
https://cdn.sparkfun.com/assets/1/d/b/f/d/WT2003S-16S_Datasheet.pdf P16.
None of those give me consistent results, ie if I change one of the files
then what I get when I use the same playTrackNumber(x) changes.
The example doesn't address this, and so far i have not been able to make
sense of it. Do you have a hint?

**Pull request merged**
